tourism/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views as auth_views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-module/', include('admin_module.urls')),
    path('user-module/', include('user_module.urls')),
    path('api-token-auth/', auth_views.obtain_auth_token, name='api-token-auth'),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_module/urls.py
from user_module import views
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from .views import initiate_payment, payment_callback

app_name = 'user_module'

router = DefaultRouter()
router.register('booking', views.BookingViewSet, basename='booking')

urlpatterns = [
    path('login_api/', views.LoginView.as_view(), name='login_api'),
    path('logout/', views.logout_page, name='logout_page'),
    path('signup/', views.sign_up, name='sign_up'),
    path('signup_api/', views.SignUpView.as_view(), name='signup_api'),
    path('home/', views.home, name='home'),
    path('login/', views.login_page, name='login_page'),

    path('', include(router.urls)),
    path('booking-list/', views.booking_list, name='booking_list'),
    path('booking-payment-update/', views.booking_payment_update, name='booking_payment_update'),

    path('download-charts/', views.download_charts_as_pdf, name='download_charts'),
    path('send-otp-email/', views.send_otp_email, name='send_otp_email'),

    path('get_context_data/', views.BookingViewSet.as_view({'get': 'get_context_data'}), name='get_context_data'),
    path('admin-module/download-bookings-excel/', views.download_bookings_excel, name='download_bookings_excel'),

    # payment process

    path('payment/proceed/', views.proceed_payment, name='proceed_payment'),

]

user_module/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, Group, Permission

from admin_module.models import TouristPlace, Hotel, DiscountCode

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifier
    for authentication instead of usernames.
    """

    def create_user(self, email, password=None, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_("The Email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)


class Users(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=240)
    dob = models.DateField(null=True, blank=True)
    contact_no = models.CharField(max_length=12, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    photo = models.ImageField(upload_to='user_photos', null=True, blank=True)
    groups = models.ManyToManyField(Group, related_name='user_profiles', verbose_name=_('groups'), blank=True,
                                    help_text=_('The groups this user belongs to. A user will get all permissions '
                                                'granted to each of their groups.'))

    user_permissions = models.ManyToManyField(Permission, related_name='user_profiles', verbose_name=_('user permissions'),
                                               blank=True, help_text=_('Specific permissions for this user.'))

    otp = models.CharField(max_length=6, null=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    def __str__(self):
        return self.username


class TourPackage(models.Model):
    name = models.CharField(max_length=100)
    discount_code = models.ForeignKey(DiscountCode, on_delete=models.SET_NULL, null=True, blank=True,
                                      related_name='user_tour_packages')
    hotels = models.ManyToManyField(Hotel, related_name='user_tour_packages')
    tourist_places = models.ManyToManyField(TouristPlace, related_name='user_tour_packages')
    number_of_days = models.PositiveIntegerField(default=0)
    number_of_nights = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = 'user_tour_package'


class Booking(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    tour_package = models.ForeignKey('admin_module.TourPackage', on_delete=models.CASCADE)
    book_date = models.DateField()
    contact_number = models.CharField(max_length=15)
    payment_screenshot = models.ImageField(upload_to="booking/payment_screenshots", null=True)
    payment_approved = models.BooleanField(default=False)
    num_rooms = models.PositiveIntegerField(default=0)
    num_adults = models.PositiveIntegerField(default=0)
    num_children = models.PositiveIntegerField(default=0)
    discountcode = models.ForeignKey(DiscountCode, on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    payment_rejected = models.BooleanField(default=False)

    class Meta:
        db_table = "booking"



class Invoice(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    invoice_number = models.CharField(max_length=50)
    invoice_date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = "invoice"

user_module/views.py
from django.contrib.auth import authenticate, login, logout
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authtoken.models import Token
from user_module.models import Users
from admin_module.models import State, TourPackage
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from rest_framework.authtoken.models import Token
from .serializers import BookingSerializer
from rest_framework import viewsets, status
import io
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import FileResponse
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from django.conf import settings
from .models import Booking
from rest_framework.decorators import action
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from io import BytesIO
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
import random
from user_module.tasks import send_otp_email_task
from django.core import serializers
import json
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import boto3

#IMPORT FROM UTILS
from user_module.utils.email import send_invoice_email, generate_invoice_pdf, send_booking_approved_email

def send_otp_email(request):
    email = request.POST.get('email')
    otp = random.randint(1000, 9999)
    user = Users.objects.get(email=email)
    user.otp = otp
    user.save()

    send_otp_email_task.delay(email, otp)
    return HttpResponse('success')

def login_page(request):
    return render(request, 'user_module/login.html')

def logout_page(request):
    logout(request)
    return redirect('login_page')

def sign_up(request):
    return render(request, 'user_module/signup.html')

def home(request):
    
    bookings = Booking.objects.all()
    approved_bookings = bookings.filter(payment_approved=True).count()
    rejected_bookings = bookings.filter(payment_rejected=True).count()
    pending_bookings = bookings.filter(payment_approved=False, payment_rejected=False).count()
    total_bookings = approved_bookings + rejected_bookings + pending_bookings

    approved_percentage = 0
    rejected_percentage = 0
    pending_percentage = 0
    if total_bookings != 0:
        approved_percentage = approved_bookings / total_bookings * 100
        rejected_percentage = rejected_bookings / total_bookings * 100
        pending_percentage = pending_bookings / total_bookings * 100

    # Data for the pie chart
    pie_data = [approved_percentage, rejected_percentage, pending_percentage]

    # Data for the bar chart
    bar_labels = ["Approved", "Rejected", "Pending"]
    bar_data = [approved_bookings, rejected_bookings, pending_bookings]

    states = State.objects.all()
    tourpackages = TourPackage.objects.all()
    token = Token.objects.get(user=request.user)
    context = {
        'authToken': f'Token {str(token)}',
        'pie_labels': bar_labels,
        'pie_data': pie_data,
        'bar_labels': bar_labels,
        'bar_data': bar_data,
        'states': states,
        'tourpackages': tourpackages,
    }

    return render(request, 'user_module/home.html', context)

def booking_payment_update(request):
    token = Token.objects.get(user=request.user)
    pk = request.GET.get('pk')
    booking = Booking.objects.get(pk=pk)
    context = {
        'booking': booking,
        'authToken': f'Token {str(token)}',
    }
    return render(request, 'booking/booking_payment_update.html', context)

def send_invoice_email(booking, invoice_pdf):
    # Render email template with booking details
    email_subject = 'Invoice for Booking'
    email_body = 'Hi! Happy travelling Please find the invoice! Make a payment and update to confrom booking'
    to = [booking.user.email]

    # Create the email message
    email_message = EmailMessage(
        email_subject,
        email_body,
        to=to,
    )
    
    # Attach the invoice PDF to the email
    email_message.attach('invoice.pdf', invoice_pdf.getvalue(), 'application/pdf')

    #email_message.send()

    # Send the email
    try:
        email_message.send()
    except Exception as e:
        return True
    return True

def generate_invoice_pdf(booking):
    buffer = io.BytesIO()

    # Create the PDF object
    p = canvas.Canvas(buffer)

    # Customize and draw the invoice contents
    p.setFont("Helvetica", 12)
    p.drawString(50, 750, "Invoice for Booking ID: {}".format(booking.id))
    p.drawString(50, 700, "Customer Name: {}".format(booking.user.username))
    p.drawString(50, 650, "Tour Package: {}".format(booking.tour_package.name))
    p.drawString(50, 600, "Booking Date: {}".format(booking.book_date.strftime("%Y-%m-%d")))
    p.drawString(50, 550, "Contact Number: {}".format(booking.contact_number))
    p.drawString(50, 450, "Number of Adults: {}".format(booking.num_adults))
    p.drawString(50, 400, "Number of Children: {}".format(booking.num_children))
    p.drawString(50, 350, "Price: ${}".format(booking.price))

    # Save the PDF
    p.showPage()
    p.save()

    # Set the buffer position to the beginning
    buffer.seek(0)

    return buffer

def download_charts_as_pdf(request):
    # Get the bookings data and calculate the necessary values for the charts
    bookings = Booking.objects.all()
    approved_bookings = bookings.filter(payment_approved=True).count()
    rejected_bookings = bookings.filter(payment_rejected=True).count()
    pending_bookings = bookings.count() - approved_bookings - rejected_bookings

    # Define the data for the pie chart
    pie_labels = ['Approved', 'Rejected', 'Pending']
    pie_data = [approved_bookings, rejected_bookings, pending_bookings]

    # Define the data for the bar chart
    bar_labels = ['Approved', 'Rejected', 'Pending']
    bar_data = [approved_bookings, rejected_bookings, pending_bookings]

    # Create the pie chart
    fig1, ax1 = plt.subplots()
    ax1.pie(pie_data, labels=pie_labels, autopct='%1.1f%%', startangle=90)
    ax1.axis('equal')

    # Create the bar chart
    fig2, ax2 = plt.subplots()
    ax2.bar(bar_labels, bar_data)

    # Create a PDF document and add the charts
    pdf_buffer = BytesIO()
    with PdfPages(pdf_buffer) as pdf:
        pdf.savefig(fig1)
        pdf.savefig(fig2)

    # Set the buffer's position to the beginning
    pdf_buffer.seek(0)

    # Generate the response with the PDF file
    response = HttpResponse(pdf_buffer, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="booking_charts.pdf"'

    return response

def send_booking_approved_email(booking):
    subject = 'Booking Approved'
    html_message = render_to_string('booking/booking_approved.html', {'booking': booking})
    plain_message = strip_tags(html_message)
    from_email = settings.DEFAULT_FROM_EMAIL
    to_email = booking.user.email

    send_mail(subject, plain_message, from_email, [to_email], html_message=html_message)


import openpyxl
from django.http import HttpResponse

def download_bookings_excel(request):
    # Get the filter parameters from the request (e.g., package ID, payment status)
    package_id = request.GET.get('package_id')
    payment_status = request.GET.get('payment_status')

    # Filter the bookings based on the selected parameters
    bookings = Booking.objects.all()
    if package_id:
        bookings = bookings.filter(package_id=package_id)
    if payment_status:
        if payment_status == 'false':
            bookings = bookings.filter(payment_approved=False)
        elif payment_status == 'true':
            bookings = bookings.filter(payment_approved=True)

    # Create a new Excel workbook and worksheet
    workbook = openpyxl.Workbook()
    worksheet = workbook.active

    # Write the headers
    headers = ['Booking ID', 'User', 'Tour Package', 'Booking Date', 'Contact Number', 'Payment Approved']
    for col_num, header in enumerate(headers, 1):
        worksheet.cell(row=1, column=col_num, value=header)

    # Write the booking details
    for row_num, booking in enumerate(bookings, 2):
        worksheet.cell(row=row_num, column=1, value=booking.id)
        worksheet.cell(row=row_num, column=2, value=booking.user.username)
        worksheet.cell(row=row_num, column=3, value=booking.tour_package.name)
        worksheet.cell(row=row_num, column=4, value=booking.book_date)
        worksheet.cell(row=row_num, column=5, value=booking.contact_number)
        worksheet.cell(row=row_num, column=6, value='Completed' if booking.payment_approved else 'Pending')

    # Create a response with the Excel file
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=bookings.xlsx'
    workbook.save(response)

    return response

# Listing HTML Pages Calls
def booking_list(request):
    token = Token.objects.get(user=request.user)
    context = {
        'authToken': f'Token {str(token)}',
        'packages': TourPackage.objects.all(),
    }
    return render(request, 'booking/booking_list.html', context)

#Start Of Class Based Views
class LoginView(APIView):

    def get(self, request):
        pass
    
    def post(self, request):
        otp = request.data.get('otp')
        email = request.data.get('email')
        password = request.data.get('password')
        username = request.data.get('username')

        # Authenticate user
        user = authenticate(request, email=email, password=password, otp=otp)
        
        if user is not None:
            # Log the user in
            login(request, user)

user_module/templates/booking/booking_approved.html
<!-- booking_approved.html -->
<html>
<body>
    <h1>Booking Approved</h1>
    <p>Your booking has been approved. Thank you for choosing our service.</p>
    <p>Booking Details:</p>
    <ul>
        <li>Booking ID: {{ booking.id }}</li>
        <li>Tour Package: {{ booking.tour_package.name }}</li>
        <li>Booked Date: {{ booking.book_date }}</li>
        <!-- Add more booking details as needed -->
    </ul>
</body>
</html>

user_module/templates/booking/booking_list.html
{% include 'user_module/base.html' %}
<br>

<!DOCTYPE html>
<html>
<head>
    <title>Bookings List</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        
        <h1>Bookings List</h1>
        {% if request.user.is_staff %}
            <p>Showing all bookings</p>
        {% else %}
            <p>Showing Bookings of {{ request.user.username }}</p>
        {% endif %}
        {% if request.user.is_staff %}
            <div>
                <label for="payment-status">Payment Status:</label>
                <select id="payment-status">
                <option value="">All</option>
                <option value="false">Pending</option>
                <option value="true">Completed</option>
                </select>
            </div>
            <div>
                <label for="package">Package:</label>
                <select id="package">
                    <option value="">All</option>
                    {% for package in packages %}
                        <option value="{{ package.id }}">{{ package.name }}</option>
                    {% endfor %}
                </select>
            </div>    
        {% endif %}    
        <table class="table">
            <thead>
                <tr>
                    <!-- <th>Booking ID</th> -->
                    <th>User</th>
                    <th>Tour Package</th>
                    <th>Booking Date</th>
                    <th>Contact Number</th>
                    <th>Payment Approved</th>
                    <!-- <th>Num Rooms</th> -->
                    <th>Num Adults</th>
                    <th>Num Children</th>
                    <!-- <th>Discount Code</th> -->
                    <th>Price</th>
                    <th>Payment Screenshot</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="bookingsList"></tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Add Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function fetchBookings(paymentStatus, package) {

            // Fetch bookings list via AJAX
            var authToken = '{{ authToken }}';

            $.ajax({
                url: '/user-module/booking/',
                method: 'GET',
                headers: {
                    "X-CSRFTOKEN": "{{ csrf_token }}",
                    "Authorization": "{{ authToken }}"
                },
                data: {
                    'payment_status': paymentStatus,
                    'package': package,
                },
                success: function(response) {
                    var bookings = response;

                    // Update the bookings table
                    var bookingsList = $('#bookingsList');
                    bookingsList.empty();

                    // Iterate over the bookings and display them in the table
                    for (var i = 0; i < bookings.length; i++) {
                        var booking = bookings[i];

                        var bookingId = booking.id;
                        console.log(booking.payment_approved);
                        var htmlContent = `
                            {% if request.user.is_staff %}
                                {% if booking.payment_screenshot %}
                                    Yet to upload payment screenshot
                                {% elif booking.payment_approved %}
                                    Approved
                                {% else %}
                                    <button class="btn btn-success approve-btn" data-booking-id="${bookingId}">Approve</button>
                                    <button class="btn btn-danger reject-btn" data-booking-id="${bookingId}">Reject</button>
                                {% endif %}
                            {% else %}
                                {% if booking.payment_screenshot is null %}
                                    <a href="{% url 'user_module:booking_payment_update' %}?pk=${bookingId}" class="btn btn-primary">Update Payment</a>
                                {% endif %}<br>

                                {% if booking.payment_approved %}
                                    Approved
                                {% elif booking.payment_rejected %}
                                    Rejected
                                {% else %}
                                    Approval in Process
                                {% endif %}
                            {% endif %}
                        `;

                        var row = `<tr>
                            <td>${booking.user_name}</td>
                            <td>${booking.tour_package_name}</td>
                            <td>${booking.book_date}</td>
                            <td>${booking.contact_number}</td>
                            <td>${booking.payment_approved}</td>
                            <td>${booking.num_adults}</td>
                            <td>${booking.num_children}</td>
                            <td>${booking.price}</td>
                            <td>
                                <img src="${booking.payment_screenshot}" alt="Payment Screenshot" width="50" height="50">
                            </td>                            
                            <td>${htmlContent}</td>
                        </tr>`;

                        // Add the row to the table body
                        bookingsList.append(row);
                    }

                },
                error: function(error) {
                    console.error('Failed to fetch bookings:', error);
                }
            });
        }
        $(document).ready(function() {
            // Fetch all bookings initially
            fetchBookings('', '');

            // Handle filter selection change
            $('#payment-status, #package').change(function() {
                var paymentStatus = $('#payment-status').val();
                var package = $('#package').val();

                // Fetch bookings based on the selected filters
                fetchBookings(paymentStatus, package);
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            var authToken = '{{ authToken }}';

            // Handle the "Approve" button click
            $(document).on('click', '.approve-btn', function() {
                var bookingId = $(this).data('booking-id');
                alert(bookingId);
                updateBookingStatus(bookingId, true); // Call the updateBookingStatus function with payment_approved = true
            });
    
            // Handle the "Reject" button click
            $(document).on('click', '.reject-btn', function() {
                var bookingId = $(this).data('booking-id');
                updateBookingStatus(bookingId, false); // Call the updateBookingStatus function with payment_approved = false
            });
    
            // Function to update the booking status via AJAX
            function updateBookingStatus(bookingId, paymentApproved) {
                $.ajax({
                url: '/user-module/booking/' + bookingId + '/mark_completed/',
                method: 'PUT',
                data: {
                    payment_approved: paymentApproved,
                },
                headers: {
                    "X-CSRFTOKEN": "{{ csrf_token }}",
                    "Authorization": "{{ authToken }}"
                },
                success: function(response) {
                    console.log('Booking status updated successfully');
                    // Perform any additional actions on success, such as displaying a success message or refreshing the page
                },
                error: function(error) {
                    console.error('Error updating booking status:', error);
                    // Handle the error in any desired way, such as displaying an error message
                }
                });
            }
        });
    
    </script>
</body>
</html>

{% if request.user.is_staff %}
    <button id="downloadExcelBtn" class="btn btn-primary booking-word">Download Excel</button>
{% endif %}

<script>
    $(document).ready(function() {
        $(document).on('click', '#downloadExcelBtn', function() {
            var selectedPaymentStatus = $('#payment-status').val();
            var selectedPackageId = $('#package').val();
            
            var downloadUrl = '{% url "user_module:download_bookings_excel" %}?package=' + selectedPackageId + '&payment_status=' + selectedPaymentStatus;
            
            // Perform the download by redirecting to the download URL
            window.location.href = downloadUrl;
        });
    });
</script>

user_module/templates/booking/booking_payment_update.html
{% include 'user_module/base.html' %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<p>User: {{ booking.user }}</p>
<p>Tour Package: {{ booking.tour_package.name }}</p>
<p>Booking Date: {{ booking.book_date }}</p>
<p>Contact Number: {{ booking.contact_number }}</p>
<p>Payment Approved: {{ booking.payment_approved }}</p>
<p>Number of Adults: {{ booking.num_adults }}</p>
<p>Number of Children: {{ booking.num_children }}</p>
<p>Price: {{ booking.price }}</p>

<form id="paymentForm" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="payment_screenshot" id="paymentScreenshot">
    <input type="hidden" name="booking_id" value="{{ booking.id }}">
    <button type="submit">Upload Payment Screenshot</button>
</form>

<script>
    // Add an event listener to the form submit event
    document.getElementById('paymentForm').addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent the default form submission
        
        // Get the form data
        var formData = new FormData(this);
        var authToken = '{{ authToken }}';
       
        // Make an AJAX request to update the payment screenshot
        $.ajax({
            url: "{% url 'user_module:booking-detail' booking.id %}",
            type: "PUT",
            data: formData,
            headers: { 
                "X-CSRFTOKEN": "{{ csrf_token }}",
                "Authorization": "{{ authToken }}"
            },
            processData: false,
            contentType: false,
            success: function (response) {
                // Handle the success response
                console.log('Payment screenshot uploaded successfully');
                // You can perform additional actions here, such as displaying a success message or refreshing the page
                window.location.href = "{% url 'user_module:booking_list' %}";
            },
            error: function (error) {
                // Handle the error response
                console.error('Error uploading payment screenshot:', error);
                // You can display an error message to the user or handle the error in any desired way
            }
        });
    });
</script>


  